[package]
name = "tiny-rpa-engine"
version = "0.1.0"
edition = "2024"

[lib]
name = "my_tiny_rpa_engine"
crate-type = ["cdylib"]

[dependencies]
winapi = { version = "0.3.9", features = ["winuser"] }
